### ISSUE TITLE
Database: Product Checklist Editing does not Remove products/platforms

### ISSUE THREAD

**Issue by Hont91** [Lysferd/potential-ironman#24]
While testing the dependencies, it was discovered that when editing the compatible products/platforms(and in my case, the dependencies) if a previously checked product/platform was unchecked, it would not be removed from the database, though adding another seems to work without problem.
- Attempted to logout and login again, there was no difference.
- Attempted to restart the `rails s', one of three choices unchecked remained so, no difference on the other two. Followed the attempt with another editing, no change.

**Comment by Lysferd** [comment]
The check box HTML form element considers the unchecked status as invalid, so it's ignored by the POST.
My guess is that when at least one element is checked, the array sent to the controller is not empty, but otherwise it is so the controller ignores it.
I'll review this over.

**Comment by Hont91** [comment]
While testing, it was discovered that there was a problem with #show not happening when using the show button, after editing the product in question, regardless of whether there is a change or not, it would work normally.
I presume it was a problem derived from the fix to the whitelist problem, likelly the change from nil to 0.
could not reproduce it for appropriate testing.

**Comment by Lysferd** [comment]
Reopened but couldn't reproduce it either. The way you describe, after changing the values of parameters like `platforms_whitelist`, #show should start to present problems, but actually everything worked just fine here.
Honestly I see no possibility for it to fail as a result of commit c486e96d1d7f764654738958569de085fa9c88f6, because that commit only alters how the model receives these attributes from the form, not how other pages treat that specific object. Also, to show an object, all that's needed is a route to it, i.e.: `products/1`, `@product`, `product_path( 1 )`, so unless the bug happens on the rendering of `show` (which in my tests worked fine), I can't fathom the source of this error.

If you notice this issue again, explain with more details and reopen this issue.
